/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(agent)'}/create-property` | `/create-property`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/biodata` | `/biodata`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding1` | `/onboarding1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding2` | `/onboarding2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/phone` | `/phone`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/roleselection` | `/roleselection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/AnimatedButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/AnimatedInput`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(agent)'}/create-property` | `/create-property`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/biodata` | `/biodata`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding1` | `/onboarding1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding2` | `/onboarding2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/phone` | `/phone`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/roleselection` | `/roleselection`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AnimatedButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AnimatedInput`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(agent)'}/create-property${`?${string}` | `#${string}` | ''}` | `/create-property${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/biodata${`?${string}` | `#${string}` | ''}` | `/biodata${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding1${`?${string}` | `#${string}` | ''}` | `/onboarding1${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding2${`?${string}` | `#${string}` | ''}` | `/onboarding2${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/otp${`?${string}` | `#${string}` | ''}` | `/otp${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/phone${`?${string}` | `#${string}` | ''}` | `/phone${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/roleselection${`?${string}` | `#${string}` | ''}` | `/roleselection${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/AnimatedButton${`?${string}` | `#${string}` | ''}` | `/components/AnimatedInput${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(agent)'}/create-property` | `/create-property`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/biodata` | `/biodata`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding1` | `/onboarding1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding2` | `/onboarding2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/phone` | `/phone`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/roleselection` | `/roleselection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/AnimatedButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/AnimatedInput`; params?: Router.UnknownInputParams; };
    }
  }
}
